### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by CRLqinliang** [kaixindelele/RHER#5]
我问一下哈。

- 在用RHER sample期间，是不是根据在经验池中0向量所在的位置来区分任务？
- 如果是你论文中所写的分为6个sub-task的话，是不是一次Update中要顺序更新6个任务的策略函数？
- 如果我想把目前给的demo改成3个Object，6任务的话需要注意哪些地方？
@kaixindelele

**Comment by kaixindelele** [comment]
1. 是的，论文里提到了这个，我称作 零填充 目标编码，用于区分任务。
2. 6个子任务的话，还是每次更新当前的，以及下一个。至于这块的代码，我还没有开源，因为我下一篇工作还在做，所以不太好开源。
3. 需要注意的点比较多，整个的代码框架用的是pytorch了，而且不能存轨迹，而是每次交互后，先目标重标记，再把所有的子任务的数据，分别存到对应的经验池中，比较复杂，细节也蛮多的。

如果你直接自己复现的话，难度有点高。我可能在年底才开源这部分的代码。

**Comment by CRLqinliang** [comment]
嗯嗯好的，谢谢。

**Comment by xcvbn123456** [comment]
> 1. 是的，论文里提到了这个，我称作 零填充 目标编码，用于区分任务。
> 2. 6个子任务的话，还是每次更新当前的，以及下一个。至于这块的代码，我还没有开源，因为我下一篇工作还在做，所以不太好开源。
> 3. 需要注意的点比较多，整个的代码框架用的是pytorch了，而且不能存轨迹，而是每次交互后，先目标重标记，再把所有的子任务的数据，分别存到对应的经验池中，比较复杂，细节也蛮多的。
> 
> 如果你直接自己复现的话，难度有点高。我可能在年底才开源这部分的代码。

@kaixindelele 您好，请问您这部分开源了吗？

**Comment by kaixindelele** [comment]
> > 1. 是的，论文里提到了这个，我称作 零填充 目标编码，用于区分任务。
> > 2. 6个子任务的话，还是每次更新当前的，以及下一个。至于这块的代码，我还没有开源，因为我下一篇工作还在做，所以不太好开源。
> > 3. 需要注意的点比较多，整个的代码框架用的是pytorch了，而且不能存轨迹，而是每次交互后，先目标重标记，再把所有的子任务的数据，分别存到对应的经验池中，比较复杂，细节也蛮多的。
> > 
> > 如果你直接自己复现的话，难度有点高。我可能在年底才开源这部分的代码。
> 
> [@kaixindelele](https://github.com/kaixindelele) 您好，请问您这部分开源了吗？

开了的，可以参考https://github.com/kaixindelele/RHER/blob/main/RHER_torch/train_torch.py
启动代码在https://github.com/kaixindelele/RHER/blob/main/RHER_torch/tune_rher_main.py

**Comment by xcvbn123456** [comment]
> > > 1. 是的，论文里提到了这个，我称作 零填充 目标编码，用于区分任务。
> > > 2. 6个子任务的话，还是每次更新当前的，以及下一个。至于这块的代码，我还没有开源，因为我下一篇工作还在做，所以不太好开源。
> > > 3. 需要注意的点比较多，整个的代码框架用的是pytorch了，而且不能存轨迹，而是每次交互后，先目标重标记，再把所有的子任务的数据，分别存到对应的经验池中，比较复杂，细节也蛮多的。
> > > 
> > > 如果你直接自己复现的话，难度有点高。我可能在年底才开源这部分的代码。
> > 
> > 
> > [@kaixindelele](https://github.com/kaixindelele) 您好，请问您这部分开源了吗？
> 
> 开了的，可以参考https://github.com/kaixindelele/RHER/blob/main/RHER_torch/train_torch.py 启动代码在https://github.com/kaixindelele/RHER/blob/main/RHER_torch/tune_rher_main.py

您好，请问torch的版本有要求吗？

**Comment by kaixindelele** [comment]
要求应该不高，你可以试试

**Comment by xcvbn123456** [comment]
> 要求应该不高，你可以试试

好的，谢谢

**Comment by xcvbn123456** [comment]
> 要求应该不高，你可以试试
您好，请问有对训练好的模型进行可视化的代码吗？

**Comment by xcvbn123456** [comment]
> > > 1. 是的，论文里提到了这个，我称作 零填充 目标编码，用于区分任务。
> > > 2. 6个子任务的话，还是每次更新当前的，以及下一个。至于这块的代码，我还没有开源，因为我下一篇工作还在做，所以不太好开源。
> > > 3. 需要注意的点比较多，整个的代码框架用的是pytorch了，而且不能存轨迹，而是每次交互后，先目标重标记，再把所有的子任务的数据，分别存到对应的经验池中，比较复杂，细节也蛮多的。
> > > 
> > > 如果你直接自己复现的话，难度有点高。我可能在年底才开源这部分的代码。
> > 
> > 
> > [@kaixindelele](https://github.com/kaixindelele) 您好，请问您这部分开源了吗？
> 
> 开了的，可以参考https://github.com/kaixindelele/RHER/blob/main/RHER_torch/train_torch.py 启动代码在https://github.com/kaixindelele/RHER/blob/main/RHER_torch/tune_rher_main.py

您好，请问有对训练好的模型进行可视化的代码吗？
